logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: debug
spring:
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.50.163.111:3306/haruharu?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
  redis:
    host: 49.50.163.111
    port: 6379
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: R3CKfkBKtVY6ajw8kJV6
            client-secret: W9T78S4aBy
            redirect-uri: http://http://49.50.163.111/:8080/oauth2/callback/naver
            client-authentication-method: post
            authorization-grant-type: authorization_code
            scope: nickname,email,profile_image
            client-name: Naver
          kakao:
            client-id: c26e0a8f2821ce1903247ac3c1f6a5e7
            client-secret: UAxzzr7hEzJa4QuGRldWS58j6tTuIag6
            redirect-uri: http://http://49.50.163.111/:8080/oauth2/callback/kakao
            client-authentication-method: post
            authorization-grant-type: authorization_code
            scope: profile_nickname,profile_image,account_email
            client-name: Kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

app:
  auth:
    tokenSecret: sangeunsangeunsangeunsangeunsangeunsangeunsangeunsangeunsangeunsangeunsangeunsangeunsangeunsangeunsangeunsangeunsangeunsangeunsangeunsangeunsangeunsangeunsangeunsangeunsangeunsangeunsangeunsangeunsangeun
    accessTokenExpirationMsec: 1800000
    refreshTokenExpirationMsec: 604800000
  cors:
    allowedOrigins: http://http://49.50.163.111/:3000, http://http://49.50.163.111/:8080
  oauth2:
    authorizedRedirectUris: http://http://49.50.163.111/:3000/oauth2/redirect

server:
  error:
    include-exception: true
    include-stacktrace: always
  port: 8080

springdoc:
  swagger-ui:
    path: swagger
    tryItOutEnabled: true
    filter: true
    operationsSorter: method
    displayRequestDuration: true
    supportedSubmitMethods: ["get", "put", "post", "options"]

clova:
  url: https://clovastudio.stream.ntruss.com/testapp/v1/chat-completions/HCX-002
  X-NCP-CLOVASTUDIO-API-KEY: NTA0MjU2MWZlZTcxNDJiY0Q+agAvO7ThcA564J17RAlpshebZTIhRYsVc/gX0I/uBNPkpPCgM8wJqKiESW6zvD6649SY1Yk8i9Smma0VqlNQnexUAmD9WKSs4x/FT+dyFg1uhzw7op3k/b/iIn/NIdkQLxRgClvARgus73DWEC+yKJKVp1dFxpl5sxyNsEnLH8nxtRDRg5ohdiUg2hy8GbHYa8SwWW4OawhaqWVqyVI=
  X-NCP-APIGW-API-KEY: IHQD7VJfELEyMar7N2Q3Lk29CvgDcQBtLabO87bM
  X-NCP-CLOVASTUDIO-REQUEST-ID: cb9f86056ca14f8d9e2924cadd6e4507

cloud:
  ncp:
    credentials:
      accessKey: RL1LdlB9p4zKGQJPeaZx
      secretKey: roIritVwMj1II1EQza67HweDfoDHnALU5MDJd9CS
    region: kr-standard
    s3:
      bucket:
        name: haruharu
        url: https://kr.object.ncloudstorage.com/haruharu